---
dist: bionic
language: python
python: "3.8"

# Use the new container infrastructure
sudo: required

env:
  global:
    - ROLE_NAME: docker_app
  matrix:
    - MOLECULE_DISTRIBUTION: ubuntu18
    - MOLECULE_DISTRIBUTION: ubuntu20
    - MOLECULE_DISTRIBUTION: debian8
    - MOLECULE_DISTRIBUTION: debian9
    - MOLECULE_DISTRIBUTION: debian10
# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  - mv "$PWD" "${PWD%/*}/$ROLE_NAME"
  # Install ansible
  # - pip install -r requirements.txt
  - pip install yamllint==1.23.0 ansible molecule

  # Check ansible version
  - ansible --version
  - ls -la /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages
  - yamllint -v
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - molecule lint
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
