---

- debug: var=docker_container

- name: Test another var name
  set_fact:
    docker_container: "{{ docker_containerr }}"

- debug:
    msg: "container {{ docker_container.name }} command {{ item }}"
  loop: "{{ docker_container.pre_release_commands | default([]) }}"


- name: Ensure pre-release command
  command:
    cmd: "echo {{ docker_container.name }}-pre-release{{ 10 | random }}"
    # command: "{{ docker_container }}"
  register: docker_command_result
  changed_when: no
  # changed_when: not command.not_changed_when_string_in_output in "j" #docker_command_result.container.Output
  with_items: "{{ docker_container.pre_release_commands | default([]) }}"
  # ignore_errors: yes
  loop_control:
    loop_var: command

#
- name: Run pre-release commands
  docker_container:
    name: "{{ docker_container.name }}-pre-release"
    image: "{{ docker_container.image }}"
    detach: no
    cleanup: yes
    state: started
    volume_driver: "{{ docker_container.volume_driver | default(docker_volume_driver_default) | default(omit) }}"
    volumes: "{{ docker_container.volumes | default(docker_volumes_default) | default(omit) }}"
    mounts: "{{ docker_container.mounts | default(docker_mounts_default) | default(omit) }}"
    env: "{{ docker_container.env | default(docker_env_default) | default(omit) }}"
    env_file: "{{ docker_container.env_file | default(docker_env_file_default) | default(omit) }}"
    network_mode: "{{ docker_container.network_mode | default(docker_network_mode_default) | default(omit) }}"
    networks: "{{ docker_container.networks | default(docker_networks_default) | default(omit) }}"
    recreate: "{{ docker_container.recreate | default(docker_recreate_default) | default(omit) }}"
    user: "{{ docker_container.user | default(docker_user_default) | default(omit) }}"
    command: "{{ command }}"
  register: docker_command_result
  # changed_when: not command.not_changed_when_string_in_output in "j" #docker_command_result.container.Output
  loop: "{{ docker_container.pre_release_commands | default([]) }}"
  # ignore_errors: yes
  loop_control:
    loop_var: command

- debug: var=docker_container


- name: "Run or stop docker container"
  docker_container:
    name: "{{ docker_container.name }}"
    image: "{{ docker_container.image | default(docker_image_default) | default(omit) }}"
    pull: "{{ docker_container.pull | default(docker_pull_default) | default(omit) }}"
    restart: "{{ docker_container.restart | default(docker_restart_default) | default(omit) }}"
    restart_policy: "{{ docker_container.restart_policy | default(docker_restart_policy_default) | default(omit) }}"
    cleanup: "{{ docker_container.cleanup | default(docker_cleanup_default) | default(omit) }}"
    working_dir: "{{ docker_container.working_dir | default(docker_working_dir_default) | default(omit) }}"
    volume_driver: "{{ docker_container.volume_driver | default(docker_volume_driver_default) | default(omit) }}"
    volumes: "{{ docker_container.volumes | default(docker_volumes_default) | default(omit) }}"
    mounts: "{{ docker_container.mounts | default(docker_mounts_default) | default(omit) }}"
    detach: "{{ docker_container.detach | default(docker_detach_default) | default(omit) }}"
    env: "{{ docker_container.env | default(docker_env_default) | default(omit) }}"
    env_file: "{{ docker_container.env_file | default(docker_env_file_default) | default(omit) }}"
    network_mode: "{{ docker_container.network_mode | default(docker_network_mode_default) | default(omit) }}"
    networks: "{{ docker_container.networks | default(docker_networks_default) | default(omit) }}"
    recreate: "{{ docker_container.recreate | default(docker_recreate_default) | default(omit) }}"
    user: "{{ docker_container.user | default(docker_user_default) | default(omit) }}"
    state: "{{ docker_container.state | default(docker_state_default) }}"
    command: "{{ docker_container.command | default(docker_command_default) | default(omit) }}"
    auto_remove: "{{ docker_container.auto_remove | default(docker_auto_remove_default) | default(omit) }}"
    blkio_weight: "{{ docker_container.blkio_weight | default(docker_blkio_weight_default) | default(omit) }}"
    capabilities: "{{ docker_container.capabilities | default(docker_capabilities_default) | default(omit) }}"
    cap_drop: "{{ docker_container.cap_drop | default(docker_cap_drop_default) | default(omit) }}"
    comparisons: "{{ docker_container.comparisons | default(docker_comparisons_default) | default(omit) }}"
    cpu_period: "{{ docker_container.cpu_period | default(docker_cpu_period_default) | default(omit) }}"
    cpu_quota: "{{ docker_container.cpu_quota | default(docker_cpu_quota_default) | default(omit) }}"
    cpuset_cpus: "{{ docker_container.cpuset_cpus | default(docker_cpuset_cpus_default) | default(omit) }}"
    cpuset_mems: "{{ docker_container.cpuset_mems | default(docker_cpuset_mems_default) | default(omit) }}"
    cpu_shares: "{{ docker_container.cpu_shares | default(docker_cpu_shares_default) | default(omit) }}"
    devices: "{{ docker_container.devices | default(docker_devices_default) | default(omit) }}"
    device_read_bps: "{{ docker_container.device_read_bps | default(docker_device_read_bps_default) | default(omit) }}"
    device_write_bps: "{{ docker_container.device_write_bps | default(docker_device_write_bps_default) | default(omit) }}"
    device_read_iops: "{{ docker_container.device_read_iops | default(docker_device_read_iops_default) | default(omit) }}"
    device_write_iops: "{{ docker_container.device_write_iops | default(docker_device_write_iops_default) | default(omit) }}"
    dns_opts: "{{ docker_container.dns_opts | default(docker_dns_opts_default) | default(omit) }}"
    dns_servers: "{{ docker_container.dns_servers | default(docker_dns_servers_default) | default(omit) }}"
    dns_search_domains: "{{ docker_container.dns_search_domains | default(docker_dns_search_domains_default) | default(omit) }}"
    domainname: "{{ docker_container.domainname | default(docker_domainname_default) | default(omit) }}"
    entrypoint: "{{ docker_container.entrypoint | default(docker_entrypoint_default) | default(omit) }}"
    etc_hosts: "{{ docker_container.etc_hosts | default(docker_etc_hosts_default) | default(omit) }}"
    exposed_ports: "{{ docker_container.exposed_ports | default(docker_exposed_ports_default) | default(omit) }}"
    force_kill: "{{ docker_container.force_kill | default(docker_force_kill_default) | default(omit) }}"
    groups: "{{ docker_container.groups | default(docker_groups_default) | default(omit) }}"
    healthcheck: "{{ docker_container.healthcheck | default(docker_healthcheck_default) | default(omit) }}"
    hostname: "{{ docker_container.hostname | default(docker_hostname_default) | default(omit) }}"
    ignore_image: "{{ docker_container.ignore_image | default(docker_ignore_image_default) | default(omit) }}"
    init: "{{ docker_container.init | default(docker_init_default) | default(omit) }}"
    interactive: "{{ docker_container.interactive | default(docker_interactive_default) | default(omit) }}"
    ipc_mode: "{{ docker_container.ipc_mode | default(docker_ipc_mode_default) | default(omit) }}"
    keep_volumes: "{{ docker_container.keep_volumes | default(docker_keep_volumes_default) | default(omit) }}"
    kill_signal: "{{ docker_container.kill_signal | default(docker_kill_signal_default) | default(omit) }}"
    kernel_memory: "{{ docker_container.kernel_memory | default(docker_kernel_memory_default) | default(omit) }}"
    labels: "{{ docker_container.labels | default(docker_labels_default) | default(omit) }}"
    links: "{{ docker_container.links | default(docker_links_default) | default(omit) }}"
    log_driver: "{{ docker_container.log_driver | default(docker_log_driver_default) | default(omit) }}"
    log_options: "{{ docker_container.log_options | default(docker_log_options_default) | default(omit) }}"
    mac_address: "{{ docker_container.mac_address | default(docker_mac_address_default) | default(omit) }}"
    memory: "{{ docker_container.memory | default(docker_memory_default) | default(omit) }}"
    memory_reservation: "{{ docker_container.memory_reservation | default(docker_memory_reservation_default) | default(omit) }}"
    memory_swap: "{{ docker_container.memory_swap | default(docker_memory_swap_default) | default(omit) }}"
    memory_swappiness: "{{ docker_container.memory_swappiness | default(docker_memory_swappiness_default) | default(omit) }}"
    networks_cli_compatible: "{{ docker_container.networks_cli_compatible | default(docker_networks_cli_compatible_default) | default(omit) }}"
    userns_mode: "{{ docker_container.userns_mode | default(docker_userns_mode_default) | default(omit) }}"
    oom_killer: "{{ docker_container.oom_killer | default(docker_oom_killer_default) | default(omit) }}"
    oom_score_adj: "{{ docker_container.oom_score_adj | default(docker_oom_score_adj_default) | default(omit) }}"
    output_logs: "{{ docker_container.output_logs | default(docker_output_logs_default) | default(omit) }}"
    paused: "{{ docker_container.paused | default(docker_paused_default) | default(omit) }}"
    pid_mode: "{{ docker_container.pid_mode | default(docker_pid_mode_default) | default(omit) }}"
    pids_limit: "{{ docker_container.pids_limit | default(docker_pids_limit_default) | default(omit) }}"
    privileged: "{{ docker_container.privileged | default(docker_privileged_default) | default(omit) }}"
    published_ports: "{{ docker_container.published_ports | default(docker_published_ports_default) | default(omit) }}"
    purge_networks: "{{ docker_container.purge_networks | default(docker_purge_networks_default) | default(omit) }}"
    read_only: "{{ docker_container.read_only | default(docker_read_only_default) | default(omit) }}"
    restart_retries: "{{ docker_container.restart_retries | default(docker_restart_retries_default) | default(omit) }}"
    runtime: "{{ docker_container.runtime | default(docker_runtime_default) | default(omit) }}"
    shm_size: "{{ docker_container.shm_size | default(docker_shm_size_default) | default(omit) }}"
    security_opts: "{{ docker_container.security_opts | default(docker_security_opts_default) | default(omit) }}"
    stop_signal: "{{ docker_container.stop_signal | default(docker_stop_signal_default) | default(omit) }}"
    stop_timeout: "{{ docker_container.stop_timeout | default(docker_stop_timeout_default) | default(omit) }}"
    trust_image_content: "{{ docker_container.trust_image_content | default(docker_trust_image_content_default) | default(omit) }}"
    tmpfs: "{{ docker_container.tmpfs | default(docker_tmpfs_default) | default(omit) }}"
    tty: "{{ docker_container.tty | default(docker_tty_default) | default(omit) }}"
    ulimits: "{{ docker_container.ulimits | default(docker_ulimits_default) | default(omit) }}"
    sysctls: "{{ docker_container.sysctls | default(docker_sysctls_default) | default(omit) }}"
    uts: "{{ docker_container.uts | default(docker_uts_default) | default(omit) }}"
    volumes_from: "{{ docker_container.volumes_from | default(docker_volumes_from_default) | default(omit) }}"
    docker_host: "{{ docker_container.docker_host | default(docker_host_default) | default(omit) }}"
    tls_hostname: "{{ docker_container.tls_hostname | default(docker_tls_hostname_default) | default(omit) }}"
    api_version: "{{ docker_container.api_version | default(docker_api_version_default) | default(omit) }}"
    timeout: "{{ docker_container.timeout | default(docker_timeout_default) | default(omit) }}"
    ca_cert: "{{ docker_container.ca_cert | default(docker_ca_cert_default) | default(omit) }}"
    client_cert: "{{ docker_container.client_cert | default(docker_client_cert_default) | default(omit) }}"
    client_key: "{{ docker_container.client_key | default(docker_client_key_default) | default(omit) }}"
    ssl_version: "{{ docker_container.ssl_version | default(docker_ssl_version_default) | default(omit) }}"
    tls: "{{ docker_container.tls | default(docker_tls_default) | default(omit) }}"
    validate_certs: "{{ docker_container.validate_certs | default(docker_validate_certs_default) | default(omit) }}"
    debug: "{{ docker_container.debug | default(docker_debug_default) | default(omit) }}"
