---

- name: Ensure old docker versions are removed
  apt:
    name:
      - docker
      - docker-engine
    state: absent

- name: Add docker apt key
  apt_key:
    url: "{{ docker_apt_key_url }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add docker apt repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    update_cache: yes
    state: present

- name: "Install {{ docker_apt_package_name }}"
  apt:
    name: "{{ docker_apt_package_name }}"
    state: present

- name: Ensure that docker is started and enabled
  systemd:
    name: "{{ docker_service_name }}"
    enabled: yes
    state: started
