---
# tasks file for docker-app
- include_tasks: install-docker.yml
  tags:
    - docker
    - docker_install
- include_tasks: git-repositories.yml
  loop: "{{ docker_app_git_repositories | default([1]) }}"
  loop_control:
    loop_var: repository
  tags:
    - docker_app
    - git
    - git_perm


- include_tasks: docker-image.yml
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: docker_image
  tags:
    - docker
    - docker_image

- include_tasks: docker-container.yml
  loop: "{{ docker_containers }}"
  loop_control:
    loop_var: container
  tags:
    - docker
    - docker_container
